version: '4.37'

services:
    web:
        build: .
        env_file:
            - .env
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/app
            - ../test:/usr/src/app/test
        command: air cmd/main.go -b 0.0.0.0
        depends_on:
          - db
          - jobe
        networks:
          - backend-network
          
    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - postgres-db:/var/lib/postgresql/data
        networks:
          - backend-network
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
        ports:
            - "8001:8001"
        depends_on:
            - db
        networks:
          - backend-network
    jobe:
        build: ./jobe  
        container_name: jobe
        ports:
            - "4000:80"
        restart: always
        networks:
            - backend-network
volumes:
    postgres-db:

networks:
  backend-network:
    driver: bridge